camunda:
  client:
#    mode: self-managed
#    tenant-id: default
#    auth:
#      client-id: demo
#      client-secret: demo
#      token-url: http://localhost:8080/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://127.0.0.1:26500
      rest-address: http://localhost:8080
      prefer-rest-over-grpc: false
#      audience: zeebe-api
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
